### ISSUE TITLE
network nat support

### ISSUE THREAD

**Issue by ivanhxq** [llamerada-jp/webrtc-cpp-sample#12]
it will be perfect if it support network nat!Need this feature very much

**Comment by llamerada-jp** [comment]
Hi, ivanhxq. This program is just a sample of data channel using WebRTC. And supporting NAT is a function of WebRTC, is not a function of each program, I think so.
In my opinion, WebRTC supported NAT, but not perfect. It is very difficult to support all patterns of networks only using P2P. TURN server helps transport over NAT. I suggest you search and prepare TURN server.
Thank you.
