### ISSUE TITLE
Nothing happens on OSX Catalina

### ISSUE THREAD

**Issue by unnikrishnan-anil** [llamerada-jp/webrtc-cpp-sample#13]
I built the code fine and I ran ./sample on two consoles. I get the following in the two consoles but nothing else. Do I need to do something else? Or is there some permission issue on Mac?

`0x10ed34dc0:Main thread`

**Comment by llamerada-jp** [comment]
It looks good. You can input some command on a console like `sdp1`, `ice1`and else, like the below document.
https://github.com/llamerada-jp/webrtc-cpp-sample/blob/master/README.en.md

**Comment by unnikrishnan-anil** [comment]
I didnt read the instructions. it works fine. Thanks.
