### ISSUE TITLE
Didn't understand this line in the code

### ISSUE THREAD

**Issue by PunitSalian** [llamerada-jp/webrtc-cpp-sample#18]
Hi Yuji, Thanks a lot for creating this simple tutorial for webrtc,I had a question for this snippet below, you are passing connection.csdo as parameter to CreateOffer, csdo is scoped_refptr but the parameter  which CreateOffer accept  is **void PeerConnection::CreateOffer(CreateSessionDescriptionObserver* observer,**  , we are passing scoped_refptr as a parameter why is it  working ? shouldn't we pass connection.csdo.get() as a parameter ?

Problem with this line below:
connection.peer_connection->CreateOffer(connection.csdo, webrtc::PeerConnectionInterface::RTCOfferAnswerOptions());

**Comment by llamerada-jp** [comment]
Hi PunitSalian.

The answer to your question is the definition below in `scoped_refptr`.

```c++
at include/api/scoped_refptr.h

operator T*() const { return ptr_; }
```

`scoped_refptr`  will act as a simple pointer when necessary without `get()` or explicit cast.

The way the value is passed in here changes, depending on the version of the WebRTC.
When I updated from an earlier version, `scoped_refptr` was necessary, but we may not have to use the `scoped_refptr` recently version.

**Comment by PunitSalian** [comment]
Thanks Yuji
