### ISSUE TITLE
C++11 support

### ISSUE THREAD

**Issue by PunitSalian** [llamerada-jp/webrtc-cpp-sample#19]
Hi Yuji, I see you set the standard to c++=14  but when I do c++=11 as I have boost support the webrtc library breaks. Is there anyway I can compile webrtc for c++11 ?

**Comment by llamerada-jp** [comment]
Hi @PunitSalian 
Sorry for the late reply. I have no idea to use WebRTC library with C++11. On the other hand, boost seems to support C++14 in boost's release note.
ref. https://www.boost.org/users/history/version_1_72_0.html
