### ISSUE TITLE
Can it connect with browser?

### ISSUE THREAD

**Issue by VinciShark** [llamerada-jp/webrtc-cpp-sample#2]
Can CPP and browser communicate though webrtc using this repo?

**Comment by llamerada-jp** [comment]
Maybe can do it, but I didn't try it yet.
Almost sample is using video stream, but this sample is using only data channel. We should prepare program on browser using only data channel to try it.

**Comment by VinciShark** [comment]
My project need c++ stream video\audio\data with Electron(node.js). I want to use webrtc, but can never find an proper example to do this. If any progress, please let me know. ありがとうございます

**Comment by VinciShark** [comment]
http://sourcey.com/webrtc-native-to-browser-video-streaming-example/
really interesting

**Comment by llamerada-jp** [comment]
It seems good.
Another idea, Use node.js's addon. Prepare rendering data on C++ part and, transfer on Electron.

**Comment by llamerada-jp** [comment]
You must not link OpenSSL with chrome's WebRTC library. The chrome is using BoringSSL forked by OpenSSL on WebRTC library. And it seems using the same api with OpenSSL. It provide incertitude action to your application. I dissipated time by this issue. Good luck.

**Comment by VinciShark** [comment]
THX

**Comment by VinciShark** [comment]
Only Node.js addon is not a good idea, because we need to run the c++ program in a cloud compute cluster. BTY, we already write tons lines of Node.js addons.
