### ISSUE TITLE
Undefined symbols for architecture x86_64:   "___darwin_check_fd_set_overflow", 

### ISSUE THREAD

**Issue by livioalves** [llamerada-jp/webrtc-cpp-sample#20]
Hi,

I download and tried to build on a Mac and I got this error.

Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      rtc::PhysicalSocketServer::WaitSelect(int, bool) in libwebrtc.a(physical_socket_server.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by llamerada-jp** [comment]
Hi,

Me too!
It may be related to macOS and Xcode's version.
- Xcode : 10.3
-  macOS : 10.14.6

I'm trying to rebuild the library and sample.

**Comment by llamerada-jp** [comment]
Hi @livioalves 

I updated the macOS and WebRTC library versions. That resolved the problem in my environment.

My environment is below:

- macOS: 10.15.7
- Xcode: 10.3
