### ISSUE TITLE
ubuntu 18.04 x64 exec ./build.sh get some error

### ISSUE THREAD

**Issue by seamanm** [llamerada-jp/webrtc-cpp-sample#23]
root@vultr:~/webrtc/06/webrtc-cpp-sample# sh build.sh
-- Configuring done
-- Generating done
-- Build files have been written to: /root/webrtc/06/webrtc-cpp-sample/build
[ 50%] Linking CXX executable sample
/root/webrtc/06/webrtc-cpp-sample/local/lib/libwebrtc.a(physical_socket_server.o): In function `rtc::SocketDispatcher::Initialize()':
physical_socket_server.cc:(.text._ZN3rtc16SocketDispatcher10InitializeEv+0x1e): undefined reference to `fcntl64'
physical_socket_server.cc:(.text._ZN3rtc16SocketDispatcher10InitializeEv+0x34): undefined reference to `fcntl64'
/root/webrtc/06/webrtc-cpp-sample/local/lib/libwebrtc.a(physical_socket_server.o): In function `rtc::SocketDispatcher::Create(int, int)':
physical_socket_server.cc:(.text._ZN3rtc16SocketDispatcher6CreateEii+0x8c): undefined reference to `fcntl64'
physical_socket_server.cc:(.text._ZN3rtc16SocketDispatcher6CreateEii+0xa2): undefined reference to `fcntl64'
/root/webrtc/06/webrtc-cpp-sample/local/lib/libwebrtc.a(physical_socket_server.o): In function `rtc::PhysicalSocketServer::WrapSocket(int)':
physical_socket_server.cc:(.text._ZN3rtc20PhysicalSocketServer10WrapSocketEi+0x7b): undefined reference to `fcntl64'
/root/webrtc/06/webrtc-cpp-sample/local/lib/libwebrtc.a(physical_socket_server.o):physical_socket_server.cc:(.text._ZN3rtc20PhysicalSocketServer10WrapSocketEi+0x91): more undefined references to `fcntl64' follow
collect2: error: ld returned 1 exit status
CMakeFiles/sample.dir/build.make:94: recipe for target 'sample' failed
make[2]: *** [sample] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sample.dir/all' failed
make[1]: *** [CMakeFiles/sample.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
root@vultr:~/webrtc/06/webrtc-cpp-sample#

**Comment by llamerada-jp** [comment]
Is it a misconfiguration?

**Comment by asdsastha** [comment]
I am getting the same issue can any of you help me out.
I am using  ubuntu 18.04
