### ISSUE TITLE
input ;  sample exit abnormal "Error on CreateSessionDescription"

### ISSUE THREAD

**Issue by mailonghua** [llamerada-jp/webrtc-cpp-sample#28]
log:
:140632329017152:init Main thread
sdp1
:140632329017152:create_offer_sdp
:140632312227392:PeerConnectionObserver::RenegotiationNeeded
:140632312227392:CreateSessionDescriptionObserver::OnSuccess
:140632312227392:PeerConnectionObserver::SignalingChange(1)
Offer sdp:begin
v=0
o=- 7682352746975474858 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE data
a=msid-semantic: WMS
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:x57X
a=ice-pwd:csM7p0GyUHE6sU+do2ucMzEw
a=ice-options:trickle
a=fingerprint:sha-256 BB:FE:62:48:F8:95:1A:12:79:D1:D9:72:1D:40:44:59:8D:ED:87:CF:E9:F3:7C:32:F4:59:24:CA:16:55:2B:C2
a=setup:actpass
a=mid:data
a=sctp-port:5000
a=max-message-size:262144
Offer sdp:end
:140632312227392:SetSessionDescriptionObserver::OnSuccess
:140632312227392:PeerConnectionObserver::IceGatheringChange(1)
:140632312227392:PeerConnectionObserver::IceCandidate
:140632312227392:PeerConnectionObserver::IceCandidate
:140632312227392:PeerConnectionObserver::IceCandidate
:140632312227392:PeerConnectionObserver::IceGatheringChange(2)
sdp3
hello
;
sdp3  parameter ;hello

:140632329017152:push_reply_sdp
:140632329017152:Error on CreateSessionDescription.
hello
Expect line: v=
:140632329017152:Answer SDP:begin
hello

Answer SDP:end

**Comment by mailonghua** [comment]
:140632329017152:Error on CreateSessionDescription.

**Comment by llamerada-jp** [comment]
Could you please read the document properly?
https://github.com/llamerada-jp/webrtc-cpp-sample/blob/master/README.en.md
