### ISSUE TITLE
TC_EXPORT SessionDescriptionInterface* CreateSessionDescription return NULL

### ISSUE THREAD

**Issue by mailonghua** [llamerada-jp/webrtc-cpp-sample#29]
Hi  I test this example,But encountered an error at runtime
LOG:
mailonghua@ubuntu  ~/workspace/webrtc/webrtc-cpp-sample/build   master ● ?  ./sample 
:140589676484416:init Main thread
sdp1
:140589676484416:create_offer_sdp
:140589659694656:PeerConnectionObserver::RenegotiationNeeded
:140589659694656:CreateSessionDescriptionObserver::OnSuccess
:140589659694656:PeerConnectionObserver::SignalingChange(1)
Offer sdp:begin
v=0
o=- 5231499645348132225 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE data
a=msid-semantic: WMS
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:R+TZ
a=ice-pwd:IwhrbTEQ4HI30ojGQc7vltZz
a=ice-options:trickle
a=fingerprint:sha-256 A1:07:2B:4C:BF:60:9B:36:60:8F:F6:02:D3:60:40:30:F8:2C:93:C4:64:FD:00:96:9B:1F:EE:9C:36:49:21:57
a=setup:actpass
a=mid:data
a=sctp-port:5000
a=max-message-size:262144
Offer sdp:end
:140589659694656:SetSessionDescriptionObserver::OnSuccess
:140589659694656:PeerConnectionObserver::IceGatheringChange(1)
:140589659694656:PeerConnectionObserver::IceCandidate
:140589659694656:PeerConnectionObserver::IceCandidate
:140589659694656:PeerConnectionObserver::IceCandidate
:140589659694656:PeerConnectionObserver::IceGatheringChange(2)
sdp3
hello
;
sdp3  parameter ;hello

:140589676484416:push_reply_sdp
:140589676484416:Error on CreateSessionDescription.
hello
Expect line: v=
:140589676484416:Answer SDP:begin
hello

Answer SDP:end

**Comment by llamerada-jp** [comment]
@mailonghua 
You are inputting `hello` as the SDP, but it is incorrect. I answered you to read the document last time. Have you tried following the documentation?
https://github.com/llamerada-jp/webrtc-cpp-sample/issues/28#issue-859756144

**Comment by mailonghua** [comment]
Sorry,I didn't read the document carefully before, and the steps in the document are correct

**Comment by mailonghua** [comment]
Thansk~
