### ISSUE TITLE
after last changes in WebRTC stack, it doesn't work

### ISSUE THREAD

**Issue by pyih** [llamerada-jp/webrtc-cpp-sample#3]
After last commits on WebRtc stack your example doesn't work. Something was changed with rtc::Thread class. I'm trying to debug what's wrong there, but still no success yet.
If you're also still interested with WebRtc, could you please help me and possible you can find out - how to fix your sample accordingly with last WebRtc changes.

**Comment by llamerada-jp** [comment]
Can you use the below archived files ?
It is archive of the header files and static link libraries, that are build with release version WebRTC sources tree (If it can be done well).
https://github.com/llamerada-jp/libwebrtc/releases
I tried to build the sample program with that archived files. And succeeded to run on macOS.
