### ISSUE TITLE
Read video files and transmit use webrtc

### ISSUE THREAD

**Issue by mailonghua** [llamerada-jp/webrtc-cpp-sample#30]
I want to ask to as question,how to use Native api to read and transmit video files, 
I have been searching for a long time and have not found relevant demors or documents
Have you been exposed to this part of the api can you help provide some suggestions and directions,
Thank You

**Comment by llamerada-jp** [comment]
I don't have knowledge about transmit videos using native API. I will use electron to avoid implement native video transfer in such cases. The code in [this project](https://github.com/shiguredo/momo) may help you to implement the program for the native environment. They only use Japanese and do not provide support, so you need to proceed on your own.

**Comment by mailonghua** [comment]
Thank you for you help and support
