### ISSUE TITLE
Creating Audio Video Channel instead of data Channel

### ISSUE THREAD

**Issue by EbramTawfik** [llamerada-jp/webrtc-cpp-sample#5]
I want to capture the screen on macOS and use an AudioVideo channel to stream it instead of using data channel. How can I do that?

**Comment by llamerada-jp** [comment]
Sorry, I didn't try it. I suggest you trying to use electron to fix it if you can.
By using electron, you can make desktop application by using web tech. And you can find and use some sample code that is written by JS.
By trying appear.in, you will recognize that you can capture the screen by web tech.
(・∀・)<good luck
