### ISSUE TITLE
How to create Xcode Project 

### ISSUE THREAD

**Issue by EbramTawfik** [llamerada-jp/webrtc-cpp-sample#6]
How can I create Xcode Project for this code Sample?

**Comment by llamerada-jp** [comment]
This project using CMake. CMake generate xcode project by below commands.
```
$ git clone <URL>
$ cd webrtc-cpp-sample
$ mkdir xcodeprj
$ cd xcodeprj
$ cmake -G Xcode ..
```
Generator missing path to libraries well. You will fix it.
