### ISSUE TITLE
getting compilation issue

### ISSUE THREAD

**Issue by vijayky88** [llamerada-jp/webrtc-cpp-sample#7]
hi while compiling i am getting following issue:

vijay-vm@ubuntu:~/webrtc-checkout/webrtc-cpp-sample$ sh build.sh 
-- The C compiler identification is Clang 6.0.1
-- The CXX compiler identification is Clang 6.0.1
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'x11'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vijay-vm/webrtc-checkout/webrtc-cpp-sample/build
Scanning dependencies of target sample
[ 50%] Building CXX object CMakeFiles/sample.dir/main.cpp.o
/home/vijay-vm/webrtc-checkout/webrtc-cpp-sample/main.cpp:2:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.
CMakeFiles/sample.dir/build.make:62: recipe for target 'CMakeFiles/sample.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/sample.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sample.dir/all' failed
make[1]: *** [CMakeFiles/sample.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Please let me know in its known issue

**Comment by llamerada-jp** [comment]
I did a similar issue in the past. I guess that is caused by std library.
Below pages may help you to resolve your situation.
https://askubuntu.com/questions/516801/clang-fails-to-compile-simple-hello-world-c-program
https://stackoverflow.com/questions/26333823/clang-doesnt-see-basic-headers
