### ISSUE TITLE
Compile webrtc to static library

### ISSUE THREAD

**Issue by HarDToBelieve** [llamerada-jp/webrtc-cpp-sample#8]
Hi,

Can I ask you about how to compile webrtc to static library? I have followed [instructions](https://webrtc.org/native-code/development/) but I didn't feel familiar with ninja so it was quite complicated for me

**Comment by llamerada-jp** [comment]
Hello!

The finished output is here (see Releases, download and unarchive it)
https://github.com/llamerada-jp/libwebrtc

Or, do you want to get the skill to compile webrtc?
If you so, you can see build process at build.py in the above repo.

**Comment by HarDToBelieve** [comment]
I've done it, thanks!
