### ISSUE TITLE
Error while build.sh

### ISSUE THREAD

**Issue by maksutovaynur** [llamerada-jp/webrtc-cpp-sample#9]
[ 50%] Building CXX object CMakeFiles/sample.dir/main.cpp.o
In file included from /home/aynur/CLionProjects/webrtc-cpp-sample/main.cpp:2:
In file included from /usr/bin/../include/c++/v1/iostream:38:
In file included from /usr/bin/../include/c++/v1/ios:216:
In file included from /usr/bin/../include/c++/v1/__locale:15:
In file included from /usr/bin/../include/c++/v1/string:500:
In file included from /usr/bin/../include/c++/v1/string_view:176:
In file included from /usr/bin/../include/c++/v1/__string:56:
In file included from /usr/bin/../include/c++/v1/algorithm:641:
/usr/bin/../include/c++/v1/type_traits:740:56: error: _Float16 is not supported on this target
template <>          struct __libcpp_is_floating_point<_Float16>    : public true_type {};
                                                       ^
/home/aynur/CLionProjects/webrtc-cpp-sample/main.cpp:114:17: warning: private field 'parent'
      is not used [-Wunused-private-field]
    Connection& parent;
                ^
/home/aynur/CLionProjects/webrtc-cpp-sample/main.cpp:161:17: warning: private field 'parent'
      is not used [-Wunused-private-field]
    Connection& parent;
                ^
2 warnings and 1 error generated.
make[2]: *** [CMakeFiles/sample.dir/build.make:63: CMakeFiles/sample.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/sample.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by llamerada-jp** [comment]
Can you compile "hello world!" using <iostream> on the same build environment?
